### ISSUE TITLE
models和data报错了

### ISSUE THREAD

**Issue by kudoudo** [Hammour-steak/GOUB#8]
![1726058397169](https://github.com/user-attachments/assets/27a1b4ab-3fc0-4f1e-a347-383b2f9b3cd3)
作者你好，我找不到这个问题出在哪里，可以帮我解答一下吗

**Comment by Hammour-steak** [comment]
直接运行就行，前面添加了系统路径，应该是IDEA没识别到包的路径

**Comment by kudoudo** [comment]
> 直接运行就行，前面添加了系统路径，应该是IDEA没识别到包的路径
好的，感谢
