### ISSUE TITLE
mask_root选取

### ISSUE THREAD

**Issue by kudoudo** [Hammour-steak/GOUB#9]
您好，请问您在inapiting时mask选取的是那种类型，可否给个连接。然后想问一下mask的图片必须是png文件吗？为什么我一直报下面这个错误。感谢您的回答！
![Uploading 微信图片_20240913154926.jpg…]()

**Comment by Hammour-steak** [comment]
你可以参考[这个](https://github.com/Algolzw/image-restoration-sde/tree/main/codes/config/inpainting/data/datasets/gt_keep_masks).
